const base='/app/FnOffice';
const status=document.getElementById('status');
const state={enabled:[],disabled:[],ops:new Map(),files:new Map()};
async function setBusy(value){const el=document.getElementById('fontBusy'),save=document.getElementById('saveAll');document.body.classList.toggle('font-is-busy',value);save.disabled=value;if(value){el.hidden=false;status.textContent='正在处理字体，等待 Docker 重启，预计 5 到 10 分钟…'}else el.hidden=true;fetch(`${base}/api/fonts/status`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({busy:value})}).catch(()=>{})}
async function restoreBusy(){try{const d=await (await fetch(`${base}/api/fonts/status`,{cache:'no-store'})).json();if(d.busy){setBusy(true);const progress=document.getElementById('saveProgress');progress.style.display='block';progress.removeAttribute('value')}else setBusy(false)}catch{setBusy(false)}}
setInterval(restoreBusy,5000);
const isFont=n=>/\.(ttf|otf|ttc|woff|woff2)$/i.test(n);
function namesFor(kind){const pending=[...state.files].filter(([,item])=>item.target===kind).map(([name])=>name);return [...new Set([...(state[kind]||[]),...pending])].sort((a,b)=>a.localeCompare(b));}
function render(kind){const q=document.getElementById(kind+'Filter').value.toLowerCase(),box=document.getElementById(kind);box.replaceChildren(...namesFor(kind).filter(n=>n.toLowerCase().includes(q)).map(name=>{const label=document.createElement('label');label.className='check-option';const input=document.createElement('input');input.type='checkbox';input.dataset.font=name;const pending=state.files.has(name),action=state.ops.get(name),span=document.createElement('span');span.textContent=`${pending?'[待上传] ':action==='delete'?'[待删除] ':action?'[待确认] ':''}${name}`;label.style.background=pending?'#e5e7eb':action==='delete'?'#fee2e2':action?'#fef3c7':'';label.append(input,span);return label}));}
function selected(kind){return [...document.querySelectorAll(`#${kind} input[data-font]:checked`)].map(x=>x.dataset.font)}
function moveName(name,from,to){state[from]=state[from].filter(x=>x!==name);if(!state[to].includes(name))state[to].push(name)}
function stage(kind,action){for(const name of selected(kind)){const pending=state.files.get(name);if(pending){if(action==='delete'){state.files.delete(name);state.enabled=state.enabled.filter(x=>x!==name);state.disabled=state.disabled.filter(x=>x!==name)}else{pending.target=action==='disable'?'disabled':'enabled';moveName(name,kind,pending.target)}continue}const current=state.ops.get(name);if(action==='delete')state.ops.set(name,'delete');else if((current==='disable'&&action==='enable')||(current==='enable'&&action==='disable'))state.ops.delete(name);else state.ops.set(name,action);if(action==='disable'&&kind==='enabled')moveName(name,'enabled','disabled');if(action==='enable'&&kind==='disabled')moveName(name,'disabled','enabled')}render('enabled');render('disabled');renderPending();status.textContent=`已暂存 ${state.ops.size+state.files.size} 项变更，请点击右下角保存并生效。`}
function renderPending(){const box=document.getElementById('pendingFiles');box.replaceChildren(...[...state.files].map(([name,item])=>{const p=document.createElement('p');p.textContent=`[待上传] ${name} -> ${item.target==='enabled'?'已启用':'已停用'}`;return p}))}
async function load(){const r=await fetch(`${base}/api/fonts`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.message||d.error);state.enabled=d.enabled||[];state.disabled=d.disabled||[];render('enabled');render('disabled');renderPending()}
for(const kind of ['enabled','disabled'])document.getElementById(kind+'Filter').oninput=()=>render(kind);document.getElementById('enabledAll').onclick=()=>document.querySelectorAll('#enabled input').forEach(x=>x.checked=true);document.getElementById('disabledAll').onclick=()=>document.querySelectorAll('#disabled input').forEach(x=>x.checked=true);document.getElementById('enabledDisable').onclick=()=>stage('enabled','disable');document.getElementById('enabledDelete').onclick=()=>stage('enabled','delete');document.getElementById('disabledEnable').onclick=()=>stage('disabled','enable');document.getElementById('disabledDelete').onclick=()=>stage('disabled','delete');
function addFiles(files){for(const file of [...files])if(isFont(file.name)&&!state.files.has(file.name)&&!state.enabled.includes(file.name)&&!state.disabled.includes(file.name))state.files.set(file.name,{file,target:'enabled'});render('enabled');render('disabled');renderPending();status.textContent=`已选择 ${state.files.size} 个字体，点击保存并生效后上传。`}
document.getElementById('chooseFiles').onclick=()=>document.getElementById('fontFiles').click();document.getElementById('chooseFolder').onclick=()=>document.getElementById('fontFolder').click();document.getElementById('fontFiles').onchange=e=>addFiles(e.target.files);document.getElementById('fontFolder').onchange=e=>addFiles(e.target.files);document.getElementById('addFonts').onclick=()=>document.getElementById('addDialog').showModal();
function conflictChoice(names){return new Promise(resolve=>{const dialog=document.getElementById('conflictDialog'),box=document.getElementById('conflictFiles');box.replaceChildren(...names.map(name=>{const p=document.createElement('p');p.textContent=name;return p}));const finish=value=>{dialog.close();resolve(value)};dialog.addEventListener('cancel',()=>{dialog.close();resolve(null)},{once:true});document.getElementById('conflictOverwrite').onclick=()=>finish('overwrite');document.getElementById('conflictSkip').onclick=()=>finish('skip');dialog.showModal()})}
async function saveAll(overwrite=[]){if(!state.files.size&&!state.ops.size){status.textContent='没有待保存的变更。';return}const form=new FormData(),targets={};for(const [name,item] of state.files){form.append('font',item.file,name);targets[name]=item.target}form.append('uploadTargets',JSON.stringify(targets));form.append('operations',JSON.stringify([...state.ops].map(([name,action])=>({name,action}))));form.append('overwrite',JSON.stringify(overwrite));const btn=document.getElementById('saveAll'),progress=document.getElementById('saveProgress');btn.disabled=true;progress.style.display='block';progress.removeAttribute('value');status.textContent='正在上传字体并应用变更，等待 Docker 重启，预计 5 到 10 分钟…';try{const r=await fetch(`${base}/api/fonts/apply`,{method:'POST',body:form}),d=await r.json();if(r.status===409&&d.error==='font_conflicts'){btn.disabled=false;progress.style.display='none';const choice=await conflictChoice(d.conflicts||[]);if(choice==='skip')for(const name of d.conflicts||[])state.files.delete(name);if(choice==='overwrite')return saveAll(d.conflicts||[]);render('enabled');render('disabled');renderPending();return choice==='skip'?saveAll([]):undefined}if(!r.ok)throw Error(d.message||d.error);progress.value=100;state.files.clear();state.ops.clear();document.getElementById('fontFiles').value='';document.getElementById('fontFolder').value='';status.textContent=d.restarted?'字体变更已保存，OnlyOffice 重启中，预计 5 到 10 分钟。':'字体变更已保存，无需重启 OnlyOffice。';await load()}catch(e){status.textContent=`保存失败：${e.message}`}finally{btn.disabled=false;setTimeout(()=>{progress.style.display='none';progress.value=0},1000)}}
document.getElementById('saveAll').onclick=()=>saveAll();
document.getElementById('saveAll').addEventListener('click',()=>setBusy(true));
const busyObserver=new MutationObserver(()=>{if(status.textContent.includes('，OnlyOffice 重启中，预计 5 到 10 分钟。'))status.textContent='字体变更已保存。';if(/已保存|保存失败|没有待保存/.test(status.textContent))setBusy(false)});
busyObserver.observe(status,{childList:true,characterData:true,subtree:true});
restoreBusy();
load().catch(e=>status.textContent=`读取失败：${e.message}`);
// Keep the completion message concise; the progress area already communicates
// that Docker restart may take several minutes.
