import { TrimApp } from '/app/FnOffice/trim-web-app.js?v=0.4.59';
const pageUrl=new URL(location.href), filePath=pageUrl.searchParams.get('path'), apiBase='/app/FnOffice';
if(pageUrl.searchParams.get('standalone')==='1')document.body.classList.add('standalone-editor');
const msg=document.getElementById('message'), auth=document.getElementById('authorize'), openStandaloneButton=document.getElementById('openStandalone'), downloadButton=document.getElementById('downloadFile'), sdk=new TrimApp();
downloadButton?.remove();
const mobileClient=/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini|mobile|phone|tablet/i.test(`${navigator.userAgent} ${navigator.platform}`);
if(mobileClient)openStandaloneButton?.remove();
let currentSessionId='', editorInstance=null, heartbeatTimer=null, lastActivityAt=Date.now(), handingOff=false, editorReady=false, reconnecting=false, reconnectAttempt=0;
const markActivity=()=>{lastActivityAt=Date.now()}; ['pointerdown','keydown','input','focus'].forEach(t=>window.addEventListener(t,markActivity,{passive:true}));
async function heartbeat(){if(!currentSessionId)return;try{await fetch(`${apiBase}/api/editor-session/${encodeURIComponent(currentSessionId)}/heartbeat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lastActivityAt,visible:document.visibilityState==='visible'}),keepalive:true})}catch{}}
function startHeartbeat(){clearInterval(heartbeatTimer);heartbeatTimer=setInterval(heartbeat,10000);void heartbeat()}
async function forceSave(){if(!currentSessionId)return;try{await fetch(`${apiBase}/api/editor-session/${encodeURIComponent(currentSessionId)}/force-save`,{method:'POST',headers:{'content-type':'application/json'},body:'{}',keepalive:true})}catch{}}
window.addEventListener('pagehide',()=>{if(!handingOff)void forceSave()});
async function openStandalone(){if(!filePath||handingOff)return;handingOff=true;openStandaloneButton.disabled=true;try{const target=new URL(location.href);target.searchParams.set('standalone','1');await sdk.ready();await sdk.openURL(target.toString(),'_blank');await sdk.close()}catch(e){handingOff=false;openStandaloneButton.disabled=false;msg.textContent=`无法打开独立编辑器：${e.message||e}`}}
if(pageUrl.searchParams.get('standalone')==='1'){openStandaloneButton.hidden=true;document.getElementById('editor-toolbar').style.display='none';document.getElementById('placeholder').style.height='100%'}else openStandaloneButton.onclick=openStandalone;
function reportError(code,description=''){if(!currentSessionId)return;const id=currentSessionId;currentSessionId='';clearInterval(heartbeatTimer);void fetch(`${apiBase}/api/editor-session/${encodeURIComponent(id)}/error`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:String(code).slice(0,32),description:String(description).slice(0,200)}),keepalive:true}).catch(()=>{})}
async function retryEditor(){if(reconnecting||!filePath)return;reconnecting=true;const delay=Math.min(15000,1000*Math.pow(2,Math.min(reconnectAttempt,4)));reconnectAttempt++;msg.textContent=`连接中断，${Math.ceil(delay/1000)} 秒后自动重连…`;try{await new Promise(r=>setTimeout(r,delay));try{editorInstance?.destroyEditor()}catch{};if(currentSessionId)reportError('reconnect');await openDoc()}finally{reconnecting=false}}
async function openDoc(){if(!filePath){msg.textContent='未收到文件路径。';return}msg.textContent=editorReady?'正在恢复连接…':'正在读取文档…';let r,d;try{r=await fetch(`${apiBase}/api/editor-session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:filePath})});d=await r.json()}catch(e){msg.textContent=`无法读取文档：${e.message||e}`;setTimeout(retryEditor,3000);return}if(!r.ok){msg.textContent=d.error==='file_access_denied'?'需要先授权当前文件。':`无法打开：${d.message||d.error}`;auth.hidden=d.error!=='file_access_denied';setTimeout(retryEditor,5000);return}currentSessionId=d.sessionId||'';startHeartbeat();d.editorConfig.events={...(d.editorConfig.events||{}),onDocumentReady(){editorReady=true;reconnectAttempt=0;msg.textContent=''},onRequestClose(){void forceSave().finally(()=>{try{editorInstance?.destroyEditor()}catch{}})},onError(ev){const x=ev?.data||{},code=x.errorCode??x.code??'unknown',desc=x.errorDescription||x.description||'';console.error('[FnOffice] OnlyOffice error',JSON.stringify({code,desc}));if(!editorReady){msg.textContent=`OnlyOffice 无法加载文档（错误代码：${code}）。`;reportError(code,desc)}else{msg.textContent='连接暂时中断，正在自动重连…';setTimeout(retryEditor,250)}}};const script=document.createElement('script'),server=String(d.browserOnlyOfficeUrl||`${apiBase}/onlyoffice`).replace(/\/$/,'');script.src=`${server}/web-apps/apps/api/documents/api.js`;script.onerror=()=>{msg.textContent='OnlyOffice 连接失败，正在自动重试…';if(!editorReady)reportError('script_load_failed');setTimeout(retryEditor,3000)};script.onload=()=>{try{editorInstance=new DocsAPI.DocEditor('placeholder',d.editorConfig);msg.textContent=''}catch(e){msg.textContent=`OnlyOffice 编辑器加载失败：${e.message||e}`;if(!editorReady)reportError('editor_init_failed',e.message);setTimeout(retryEditor,3000)}};document.head.appendChild(script)}
auth.onclick=async()=>{if(!filePath)return;auth.disabled=true;try{await sdk.ready();if(sdk.isStandaloneWeb){await sdk.openAppAuth('authorizeUserFile',{appName:'FnOffice',path:filePath,redirectUri:`${apiBase}/auth-callback.html`,state:filePath},{target:'_self'});return}const result=await sdk.authorizeUserFile(filePath);if(result?.code&&result.code!==0)throw new Error(result.msg||'授权未完成');await openDoc()}catch(e){msg.textContent=`无法申请文件授权：${e.message||e}`}finally{auth.disabled=false}};
openDoc();
