const api='/app/FnOffice'; const params=new URLSearchParams(location.search); let admin=params.get('all')==='1'; let records=[];
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/app/FnOffice/shares.css">');
const $=id=>document.getElementById(id); const fmtSize=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`; const fmtDate=n=>new Date(n).toLocaleString();
function render(){const q=$('query').value.toLowerCase(),from=$('from').value,to=$('to').value,st=$('status').value,ow=$('owner').value.toLowerCase(),children=$('children').checked; let list=records.filter(r=>(!q||r.fileName.toLowerCase().includes(q)||r.path.toLowerCase().includes(q))&&(!ow||String(r.ownerUsername||r.ownerUid).toLowerCase().includes(ow))&&(!from||r.createdAt>=Date.parse(from))&&(!to||r.createdAt<Date.parse(to)+86400000)&&(!children||r.path.includes('/'))&&(st==='all'||(st==='revoked'&&!r.active)||(st==='readonly'&&r.active&&!r.permissions.download&&!r.permissions.write)||(st==='download'&&r.active&&r.permissions.download)||(st==='editable'&&r.active&&r.permissions.write))); $('rows').innerHTML=list.length?list.map(r=>`<tr><td data-label="文件名">${esc(r.fileName)}</td><td data-label="路径" class="path-cell" title="${esc(r.path)}">${esc(r.path)}</td>${admin?`<td data-label="所有者">${esc(r.ownerUsername||r.ownerUid)}</td>`:''}<td data-label="大小">${fmtSize(r.size)}</td><td data-label="专属链接"><textarea readonly>${esc(r.url)}</textarea></td><td data-label="分享创建日期">${fmtDate(r.createdAt)}</td><td class="actions-col"><div class="row-actions"><button data-action="open" data-token="${r.token}" data-path="${encodeURIComponent(r.path)}">打开</button><button data-action="download" data-token="${r.token}" data-path="${encodeURIComponent(r.path)}">下载</button><button data-action="settings" data-token="${r.token}" data-path="${encodeURIComponent(r.path)}">${r.active?'设置':'重新分享'}</button><button data-action="copy" data-url="${esc(r.url)}">复制链接</button><button data-action="clear" data-token="${r.token}">清除记录</button></div></td></tr>`).join(''):`<tr><td colspan="7">暂无分享记录</td></tr>`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function load(){const r=await fetch(`${api}/api/share-records?all=${admin?'1':'0'}`,{cache:'no-store'});const d=await r.json();if(!r.ok){$('status').textContent=d.error||'读取失败';return}records=d.records||[];$('adminToggle').hidden=!d.admin;$('owner').hidden=!d.admin;document.querySelector('.owner-col').hidden=!d.admin;$('status').textContent=admin?'管理员视图：全部用户分享记录':'个人视图';render();}
document.querySelector('.share-filters').addEventListener('input',render);$('refresh').onclick=load;$('adminToggle').onclick=()=>{location.search=admin?'':'?all=1'};
$('rows').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='open')location.href=`${api}/open?path=${b.dataset.path}`;if(a==='download')location.href=`${api}/share/${encodeURIComponent(b.dataset.token)}/download`;if(a==='copy'){try{await navigator.clipboard.writeText(b.dataset.url);$('status').textContent='链接已复制';}catch{$('status').textContent='请手动复制链接';}}if(a==='settings'){location.href=`${api}/open?path=${b.dataset.path}&manageShare=${encodeURIComponent(b.dataset.token)}`;}if(a==='clear'&&await confirmModal('清除后将关闭此分享链接并删除记录，下一次分享将视为第一次。')){const r=await fetch(`${api}/api/share-records?token=${encodeURIComponent(b.dataset.token)}`,{method:'DELETE'});if(r.ok)load();}});
function confirmModal(message){return new Promise(resolve=>{const d=document.createElement('dialog');d.className='share-dialog';d.innerHTML='<form method="dialog"><h2>确认操作</h2><p class="share-dialog-hint"></p><div class="share-dialog-actions"><button value="cancel">取消</button><button class="editor-toolbar-button" value="ok">确定</button></div></form>';d.querySelector('p').textContent=message;document.body.append(d);d.addEventListener('close',()=>{resolve(d.returnValue==='ok');d.remove()},{once:true});d.showModal();});}
load();
